### ISSUE TITLE
Lift restrictions on the left-hand-side in the ES5 parser

### ISSUE THREAD

**Issue by achudnov** [jswebtools/language-ecmascript#40]
Right now the expressions that are used as targets of assignments are validated against the [`validLHS` function](https://github.com/jswebtools/language-ecmascript/blob/9dc1698ee7124df419ecb2610eb1b15cf80de94b/src/Language/ECMAScript5/Parser.hs#L157). While there is reason in that (all other expressions would raise a `ReferenceError` at run-time), the specification is less restrictive on this matter, and we'd like to follow it closely.

Thus, `assignmentExpressionGen` should be rewritten to expect any `LeftHandSideExpression` (as defined by the spec) instead of just a variable or a field reference.

When issue #41 is closed we could relax the restriction in the spec to allow error recovery.

**Comment by achudnov** [comment]
I'm not sure fixing this makes sense anymore: the ECMAScript 6 standard now imposes additional syntactic restrictions (IsValidSimpleAssignmentTarget in Static Semantics) that seem to be equivalent to the restrictions we already have. While we are not working on a extending the parser to ECMAScript 6, being too pedantic about the 5th edition of the specification makes no sense if the newer edition already imposes those restrictions. I'll give a few weeks for comments. If noone opposes, I'll close this issue as a WONTFIX.

**Comment by philipnilsson** [comment]
Agreed.
