### ISSUE TITLE
Function in while loop

### ISSUE THREAD

**Issue by philipnilsson** [jswebtools/language-ecmascript#47]
This test case:
  while (0) function n() { }

How does the standard say we should parse this? At first I thought it'd be

    Statement -> ExpressionStatment -> Expression -> FunctionExpression

the problem is ExpressionStatement has lookahead </- { '{', 'function' }, so how do you arrive at a parse for this?

**Comment by achudnov** [comment]
Having a fresh look, this test case is invalid, as Michael implied.
