### ISSUE TITLE
Infix operator parsing inside brackets: parsing "x++&256" inside of "[]"

### ISSUE THREAD

**Issue by davdar** [jswebtools/language-ecmascript#58]
This expression fails to parse:

    o[x++&256]

whereas this expression succeeds:

    o[x++ &256]

This issue is not present outside of "[]", meaning this expression parses successfully:

    x++&256

I found this by trying to parse the JSAI benchmark suite from the http://www.cs.ucsb.edu/~benh/research/downloads.html.  If you download the project files for "JSAI: A Static Analysis Platform for JavaScript" and locate the benchmarks at error/src/test/resources/FSE_benchmarks, the file that first fails to parse is opn-rsa.js.

Your tools rock by the way!  Thanks for sharing them :)

**Comment by achudnov** [comment]
This doesn't seem to affect the current tip of 'es5', so I'm closing. Please, reopen if you still can get it to fail.
