### ISSUE TITLE
Module Rename Language.ECMAScript3.* -> Language.ECMAScript.*

### ISSUE THREAD

**Issue by MetaMemoryT** [jswebtools/language-ecmascript#62]
Since we plan on supporting ECMAScript 5 should the modules be renamed to Language.ECMAScript rather than Language.ECMAScript3?

**Comment by MetaMemoryT** [comment]
oh I see the es5 branch now.

**Comment by achudnov** [comment]
I'm not married to the naming convention. Eventually, the es5 branch is going to supersede the current and there won't be the Language.ECMAScript namespace anymore. So, I wouldn't mind dropping the version number and call it Language.ECMAScript. I'd like to hear what the other users think, though.
