### ISSUE TITLE
Backporting the new pretty printer?

### ISSUE THREAD

**Issue by evancz** [jswebtools/language-ecmascript#64]
**Question:** If someone backported the new pretty printer to work with 0.17, would you accept that as a PR and release a 0.17.1 with the nicer version?

**Context:** I have been using this library for generating JS code for Elm for a while now. The API is great, but the pretty printer in the latest public release is pretty odd. JS folks tend to look at the generated code and want it to look like a human wrote it, which is a shame because I know it could.

At some point I tried out the new pretty printer that is slated to come out with 1.0, and IIRC it was a ton better. It looks like that release has been blocked on some issues for quite a long time though. I was thinking through how to unblock things for our case (use AST, use pretty printer) with @rtfeldman and came up with the backport idea.

**Comment by rtfeldman** [comment]
+1 - would be great to have pretty printing independent of the other 1.0 features!

**Comment by achudnov** [comment]
Hi Evan and Richard,
Yes, I'll accept a PR for backporting the pretty-printer, provided it doesn't break anything (which it shouldn't). Also, if you can improve the aesthetic quality of pretty-printing, that would be most welcome too. If you need to switch to a different pretty-printing library for that, that's fine too. Although, AFAIK, wl-pprint is still the best choice.

Regarding the 1.0 (actually, it's going to be 5.1, but w/e) release: I've been using it internally and I'm still planning to release it once I get time to sort through the parser bugs and finish the new test-suite. We've made headway in both directions, but thing still need to be finished and retested. Obviously, I could use some help there too.

Thanks, and let me know if you have any more questions.

**Comment by achudnov** [comment]
One more thing: please, submit the PR against the 'dev' branch.

**Comment by evancz** [comment]
And just to verify, the `dev` branch is 0.17.0.1 and could be released as 0.17.1 easily?

I was expecting we would work from the 0.17.0.1 tag and maybe have to create a new branch on this repo off of that particular commit. Is this not the case?

**Comment by achudnov** [comment]
I've just brought `dev` up to date with `master` and `0.17.0.1`. You 
could branch off wherever you like, but I'd prefer merging to be done on 
the `dev` branch --- hence my request for PR's to be based off it.

**Comment by achudnov** [comment]
Haven't seen any progress on this, so I'm closing it.

**Comment by achudnov** [comment]
FYI, an improved pretty-printer, courtesy of @Peaker, is planned for release as 0.17.1.0. See #78

**Comment by evancz** [comment]
Great, thanks for the update!
